### ISSUE TITLE
SourceDescription.sortKey is described in both the Records and RS spec

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx-record#2]
SourceDescription.sortKey is described in both the [Records](https://github.com/FamilySearch/gedcomx-record/blob/master/specifications/record-specification.md#33-extensions-to-the-sourcedescription-data-type) and [RS](https://github.com/FamilySearch/gedcomx-rs/blob/master/specifications/rs-specification.md#sort-key-property) spec. Is intended to be part of both specs or should it only be part of one?

**Comment by stoicflame** [comment]
I think it's okay to leave it in there; it has application to both contexts. It's important for records to preserve record order and it's important to RS for client-side sorting purposes. It doesn't conflict, so I think it's okay to leave it in both.

Thanks for the report, though.
